### ISSUE TITLE
Perception Numbers Don't Match

### ISSUE THREAD

**Issue by Bryan-Legend** [Larkinabout/fvtt-token-action-hud-pf2e#142] opened 2024-05-04 04:16 UTC
<img width="597" alt="Screenshot 2024-05-02 203041" src="https://github.com/Larkinabout/fvtt-token-action-hud-pf2e/assets/920120/377e416f-2605-4d19-b146-053ef00c6569">

![Screenshot 2024-05-02 203209](https://github.com/Larkinabout/fvtt-token-action-hud-pf2e/assets/920120/c6751562-9caf-468c-ac42-e2be3600c26a)

The Perception roll on the action hud is not including item or circumstance modifiers.

**Comment by Silvertower** [comment] 2024-05-10 15:56
Thank you for the report. This is caused by a limitation in what PF2E System reports using the actor's perception tooltip data. There are actually multiple different things going on here.

1. The "Eye Slash" bonus at the bottom of the second screenshot is a manually added bonus, and is not provided by the item. You can tell by the X in a circle icon to the right of it. While this manual bonus is always in effect for Perception rolls, it is not returned by the actor's perception tooltip data, which is what Token Action HUD uses. I will see about adding logic to pick up manual bonuses, assuming I can find where they are stored on the actor's data.
2. Battlefield Surveyor and Incredible Initiative (and other +perception on initiative feats) also do not appear in the perception tooltip data, and logic to pick these up will need to be added.
3. Only bonuses that are set to "enabled" are shown in the tooltip, as this is the only thing Token Action HUD can be "sure of" when the tooltip is being built. So, "Eye Slash (Major)" and "Incredible Initiative" won't show up in the tooltip data that Token Action HUD shows, since they can only be enabled via the roll dialog when an actual roll is being made. While it would be possible to show them in the tooltip with a note that they are disabled, this just clutters the tooltip, so I think the current behavior of not showing them is correct.

**Comment by Silvertower** [comment] 2024-05-10 16:02
Luckily, this was an easier fix than expected. PF2E System provides an actor.initiative dataset, which works as a direct substitution for actor.perception (which Token Action HUD was using previously) and picks up the tooltip data without any further logic changes required.

This issue will be fixed in the next release of Token Action HUD 2E.

**Closed** 2024-05-10 16:09 UTC
Labels: enhancement

**Comment by Bryan-Legend** [comment] 2024-05-10 16:52
Thank you.

Are there any other numbers that could be out of sync still? I'm
mistrustful now that I played a dozen sessions using the wrong init.

**Comment by Silvertower** [comment] 2024-05-10 17:07
I do not know. But feel free to report any you find.
