### ISSUE TITLE
[BUG] HUD buttons not showing proper info and can't read some info

### ISSUE THREAD

**Issue by biggusbeardus** [Larkinabout/fvtt-token-action-hud-pf2e#88] opened 2023-09-02 00:29 UTC
**Describe the bug**
The module is not showing some attacks as it should. Instead the button says "NaN". When you hover over a button, the tooltip box comes up , but some information is blacked out and cannot be read. Weapon icons are missing for NPCs/creatures. The buttons still work if you click them. They are just not displaying properly.

![Token_Action_HUD_Buttons_Messed_up](https://github.com/Larkinabout/fvtt-token-action-hud-core/assets/42783879/b86d0b61-cc22-4705-87b2-e31d27cd344c)

![Token_Action_HUD_Mission_Icons](https://github.com/Larkinabout/fvtt-token-action-hud-core/assets/42783879/c77876cb-4151-401b-a9ae-6133b2ef0ae0)

![Token_Action_HUD_too dark](https://github.com/Larkinabout/fvtt-token-action-hud-core/assets/42783879/43f82eb1-1f94-4b1e-8d83-af9120edacb3)

**Steps to reproduce**
1. Go to a game.
2. Click on an actor's token
3. Look at the HUD buttons.

**Versions:**
- Token Action HUD Core: 1.4.18
- Token Action HUD System: Pathfinder 2e 1.4.13
- System: Pathfinder 2e
- Foundry VTT: v11.308
- Browser: Chrome

**Additional context**
Everything was working before the Pathfinder 2e system update 5.4.1. I'm using 5.4.2 now. This occurs with all other modules off.

**Comment by Larkinabout** [comment] 2023-09-02 06:24
Duplicate of #84.

**Closed by Larkinabout** 2023-09-02 06:24 UTC
Labels: bug

**Comment by Korwyn** [comment] 2023-09-02 21:02
repasting my comment from #84, issue for Not a Number NaN

Here is the problem code for:

l = i.label.includes(e.api.Utils.i18n("PF2E.MAPAbbreviationLabel").replace(" {penalty}", "")) ? game.system.version < "5.2.0" ? n.totalModifier + parseInt(i.label.split(" ")[1]) : parseInt(i.label.split(" ")[0]) : parseInt(i.label.split(" ")[1])

Minimizing your Javascript just makes it harder to debug. The issue happens when you are splitting your label and comparing game versions. Perhaps the label changed somehow. I am not sure what changed from before. I fixed the appearance on my local version with changing the final parseInt(i.label.split(" ")[1] back to a 0. It tried to find a value in the array which doesn't exist, adds it to the totalModifier and gets NaN as a result.

I changed the final parseInt(i.label.split(" ")[1] to be parseInt(i.label.split(" ")[0]

I am not sure if this breaks on older versions of Foundry. This is what this line of code looks like for me now (just the end changed)

l = i.label.includes(e.api.Utils.i18n("PF2E.MAPAbbreviationLabel").replace(" {penalty}", "")) ? game.system.version < "5.2.0" ? n.totalModifier + parseInt(i.label.split(" ")[1]) : parseInt(i.label.split(" ")[0]) : parseInt(i.label.split(" ")[0])
