### ISSUE TITLE
PF2 5.4.0, Strike modifier has changed (shows NaN)

### ISSUE THREAD

**Issue by apoapostolov** [Larkinabout/fvtt-token-action-hud-pf2e#84] opened 2023-08-29 16:45 UTC
As simple as the title above, the strike modifier on strikes no longer shows the modifier value in the just-released new core version.

**Comment by Korwyn** [comment] 2023-08-31 06:57
seconded, this is happening to me as well

**Comment by devfinnd** [comment] 2023-08-31 07:50
thirded, mee too

**Comment by Larkinabout** [comment] 2023-08-31 09:17
Yeah, it'll be a change in PF2e 5.4.0. Will have a look when I have some time.

**Comment by Korwyn** [comment] 2023-09-02 04:27
Here is the problem code:

l = i.label.includes(e.api.Utils.i18n("PF2E.MAPAbbreviationLabel").replace(" {penalty}", "")) ? game.system.version < "5.2.0" ? n.totalModifier + parseInt(i.label.split(" ")[1]) : parseInt(i.label.split(" ")[0]) : parseInt(i.label.split(" ")[1])

Minimizing your Javascript just makes it harder to debug. The issue happens when you are splitting your label and comparing game versions. Perhaps the label changed somehow. I am not sure what changed from before. I fixed the appearance on my local version with changing the final parseInt(i.label.split(" ")[1] back to a 0. It tried to find a value in the array which doesn't exist, adds it to the totalModifier and gets NaN as a result.

I changed the final parseInt(i.label.split(" ")[1] to be parseInt(i.label.split(" ")[0]

I am not sure if this breaks on older versions of Foundry. This is what this line of code looks like for me now (just the end changed)

l = i.label.includes(e.api.Utils.i18n("PF2E.MAPAbbreviationLabel").replace(" {penalty}", "")) ? game.system.version < "5.2.0" ? n.totalModifier + parseInt(i.label.split(" ")[1]) : parseInt(i.label.split(" ")[0]) : parseInt(i.label.split(" ")[0])

**Comment by badgkat** [comment] 2023-09-05 21:38
Experiencing the same issue

**Comment by apoapostolov** [comment] 2023-09-06 08:49
Any chance we can get a fix soon?

**Comment by biggusbeardus** [comment] 2023-09-06 15:43
Any update on this bug?

**Comment by Larkinabout** [comment] 2023-09-11 16:14
Ah, yes, they're structured differently... awesome. I'll have a look to see if it's possible to not use the label as it relies too much on it being and staying consistent. If not, I might dump the feature as it's probably not doing much anymore with PF2e showing the calculated modifier by default now.

**Comment by Larkinabout** [comment] 2023-09-11 18:35
Fixed in Token Action HUD Pathfinder 2 1.4.15 (hopefully). Label is still used as trying to get the modifier elsewhere is convoluted.

**Closed by Larkinabout** 2023-09-11 18:35 UTC

**Comment by terrybjr** [comment] 2023-09-11 18:38
> Fixed in Token Action HUD Pathfinder 2 1.4.15 (hopefully). Label is still used as trying to get the modifier elsewhere is convoluted.

Confirmed, Fixed!

Thanks!
![image](https://github.com/Larkinabout/fvtt-token-action-hud-pf2e/assets/44714406/f30fe1ca-d83f-40e8-90b6-1d3ae3e75c7d)
