### ISSUE TITLE
Unable to correctly recognize spell lists in character sheets. Will treat all lists into one list.

### ISSUE THREAD

**Issue by LiyuNodream** [Larkinabout/fvtt-token-action-hud-pf2e#83] opened 2023-08-28 06:57 UTC
The sorting funcation seems to be broken. Hope you can fix it.

When you only have one Prepared, Spontaneous or Innate Spell list. It will function normally. But once you made another spell list. The new list will absorb all the spells in the action hud.

For example: The first list is  Arcane Prepared, it will show rightly. But when you add the second Arcane Focus list, then there will only be one list (focus list) in the action hud. And you can't even change it manually. Seems the Focus spell list have the hightest priority, it will absorb other spell list.

Example 2 : The first list is Primal Innate, show rightly. But when you add the second Arcane Spontaneous list, it will absorb the innate too. 

I dont know the excatly reason in the error. 

Please fix it x(

I'm not show whether this F12 error is related to the situation.
![image](https://github.com/Larkinabout/fvtt-token-action-hud-pf2e/assets/110900345/197c6fc5-5270-42ea-9059-a9ffefef9b6e)

My module version (core and pf2e hud) is the latest.
Foundry 11.307
pf2e latest

**Comment by Silvertower** [comment] 2024-01-16 17:54
Unable to reproduce. Please provide more information.

**Comment by Silvertower** [comment] 2024-01-23 17:10
Closing as cannot reproduce.

**Closed by Silvertower** 2024-01-23 17:10 UTC
