### ISSUE TITLE
[BUG] Menu not appearing when selecting token

### ISSUE THREAD

**Issue by Guolfo** [Larkinabout/fvtt-token-action-hud-pf2e#124] opened 2023-11-17 09:32 UTC
When I select a PC token who casts spells the menu doesn't appear.
If I select a PC token with a martial class (like rogue or fighter) the menu appears, but it doesn't appear nor updates If I select a PC who casts spell before.
When I select a NPC token the HUD appears but it doesn't update anymore if I select a PC token and then select a new NPC.
 
**Steps to reproduce**
1. Select a NPC token
2. Select a PC token
3. The hud doesn't update to the PC.
4. Select a NPC token different from the one on step 1
5. The hud doesn't update to the new NPC.

**Versions:**
- Token Action HUD Core 1.5.2
- Token Action HUD Pathfinder 2e 1.5.2
- Pathfinder 5.9.1
- Foundry VTT 11 build 315
- Google Chrome  119.0.6045.159

**Additional context**
Edit to add a detail about the bug about casters
If you have further questions, let me know.

**Comment by Larkinabout** [comment] 2024-02-02 15:54
Seems specific to PF2e. Make sure you're on the latest versions of Token Action HUD Core and Token Action HUD Pathfinder 2, then report back if this is still an issue.

**Comment by Silvertower** [comment] 2024-03-15 07:01
Closing as Cannot Reproduce.

**Closed by Silvertower** 2024-03-15 07:01 UTC
Labels: cannot reproduce, blocked
